name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Linting
      id: linting
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Linting
        setup-command: npm install
        command: npm run lint
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LINTING_RESULTS: "${{steps.linting.outputs.result}}"
      with:
        runners: linting
